//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MANAGMENT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laptop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Laptop()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int LaptopID { get; set; }
        public string Brand { get; set; }
        public string LaptopName { get; set; }
        public Nullable<long> Price { get; set; }
        public string Colour { get; set; }
        public string RAM_Hardisk { get; set; }
        public string OperatingSystem { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
